+ add method eventWrapper() to eliminate all self=this and curry returned function for event listeners
ControlNet/wt-data-project.web pull request #5
Opened 2022-11-22 00:18 UTC by n0099

* now listening more generic pointer events which including both touch and mouse events @ init
* rename all event listeners from `eventnameEvent` to `onEventName`
@ `plot/br-heatmap.ts`.BrHeatmap

2022-11-22 02:15 UTC, ControlNet reviewed
Line 49: Please remove unnecessary `console.log`.

Please consider to edit `/src/plot/line-chart-ts` as well.

2022-11-23 21:43 UTC, ControlNet requested changes
Type checking error. Please revise the code.

2022-11-23 22:14 UTC, ControlNet commented
Need revise the event listeners in `line-chart.ts`.

2022-11-24 08:28 UTC, n0099 commented on src/plot/line-chart.ts
> +    get brHeatmap(): BrHeatmap {
all getters are useless since u are not defining a corresponding setter method

2022-11-24 17:24 UTC, ControlNet reviewed
![image](https://user-images.githubusercontent.com/12800094/203839459-5f90264d-23c7-4e34-85d5-ed7d574f5c56.png)

It looks doesn't work on my end. Do you have any idea?

2022-11-25 01:07 UTC, n0099 commented
> ![image](https://user-images.githubusercontent.com/12800094/203839459-5f90264d-23c7-4e34-85d5-ed7d574f5c56.png)
> 
> It looks doesn't work on my end. Do you have any idea?

but `webpack build` will success without any ts error/warn

2022-11-25 06:43 UTC, ControlNet requested changes
Need revision.

2022-11-25 06:43 UTC, ControlNet commented on src/plot/br-heatmap.ts
> +            Promise.resolve((cb.bind(this) as T)(d, n[i])).then(() => {});
The tooltip doesn't work after updating. Please revise it.

br-heatmap.ts:69 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'update')
    at Function.<anonymous> (br-heatmap.ts:69:28)
    at step (color-map-def.ts:44:68)
    at Object.next (color-map-def.ts:44:68)
    at color-map-def.ts:44:68
    at new Promise (<anonymous>)
    at __webpack_modules__../src/plot/br-heatmap.ts.__awaiter (color-map-def.ts:44:68)
    at __webpack_modules__../src/plot/br-heatmap.ts.BrHeatmap.onPointerMove (br-heatmap.ts:68:60)
    at SVGRectElement.<anonymous> (br-heatmap.ts:51:49)
    at SVGRectElement.<anonymous> (on.js:27:1)

2022-11-26 18:17 UTC, ControlNet approved these changes

2022-11-26 18:47 UTC, merged